[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-voiceover-backend"
version = "0.1.0"
description = "FastAPI backend for AI Voiceover Easy"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["app"]
include-package-data = true
